version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    environment:
      - DJANGO_URL=http://web:8000
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Taipei
    networks:
      - shared-network
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  shared-network:
    external: true